# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridearranger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_make',
            new_name='make',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
