# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridearranger', '0002_auto_20180305_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ridearranger.Car'),
        ),
    ]
