# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridearranger', '0004_scenario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scenario',
            new_name='ScenarioRule',
        ),
    ]
