# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridearranger', '0006_scenariorule_group_by_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariorule',
            name='group_by_rule',
            field=models.CharField(choices=[('dest', 'Destination Location'), ('src', 'Source Location')], max_length=20),
        ),
    ]
